<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PdfEditor.Pdf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PdfSharp" />
    <PackageReference Include="PDFtoImage" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PdfEditor.Core\PdfEditor.Core.csproj" />
  </ItemGroup>
</Project>
