<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PdfEditor.Platform</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PdfEditor.Core\PdfEditor.Core.csproj" />
    <ProjectReference Include="..\PdfEditor.Pdf\PdfEditor.Pdf.csproj" />
  </ItemGroup>
</Project>
