<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PdfEditor.Ocr</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tesseract" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PdfEditor.Core\PdfEditor.Core.csproj" />
  </ItemGroup>
</Project>
